sokkanen/Lukuvinkkikirjasto

build.gradle
settings.gradle
src/main/java/dtt/lukuvinkkikirjasto/demo/LukuvinkkikirjastoApplication.java
src/main/java/dtt/lukuvinkkikirjasto/demo/database/Database.java
src/main/resources/db/migration/V1__Initial_tables.sql

* Added Sqlite as a dependency
* Added FlyWay as a dependency
* Created Database - class. Currently holds one method. To be used with the actual db-connection.
* Created first tables with "V1__Initial_tables.sql". Following database - migrations are added to the same folder (resource/db/migrate) and named sequentially (eg. V2__Some_db_operation, V3__Another_operation). Do not modify previously created .sql -files. Create a new migration file instead.

Flyway migration, Sqlite dependency, Database class

---

build.gradle
src/main/java/dtt/lukuvinkkikirjasto/demo/LukuvinkkikirjastoApplication.java
src/test/java/dtt/lukuvinkkikirjasto/demo/BaseTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/DatabaseTest.java
src/test/resources/clear-all-tables.sql

* BaseTest and DatabaseTest -classes.
* clear-all-tables -script to erase all data between tests

Created BaseTest and DatabaseTest -classes.

---

.circleci/config.yml
build.gradle

CircleCI ja Codecov. Lisään badget kunhan testaan ensin toimivuuden.

Circle and Codecov dependencies.

---

.circleci/config.yml
README.md
build.gradle
src/test/java/dtt/lukuvinkkikirjasto/demo/BaseTest.java

* Badges
* Improvements to BaseTest
* Remove duplicate JUnit

Badges and remove duplicates

---

build.gradle
src/main/java/dtt/lukuvinkkikirjasto/demo/LukuvinkkikirjastoApplication.java
src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/Dao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/database/Database.java
src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Book.java
src/main/resources/templates/books.html

Created controller for showing books and adding, fixing the database issue with sokkanen and added some entitys for classes. added "imports" for thymeleaf

Controller

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java

moves /books to front-page

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Book.java
src/main/resources/templates/books.html

Lisää mahdollisuuden validoida kirjoja, refaktoroi vähän controlleria. 
Book ei enää ota read construktorista, vaan se setataan.

Adds validation for book

---

src/main/java/dtt/lukuvinkkikirjasto/demo/LukuvinkkikirjastoApplication.java
src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/database/Database.java
src/test/java/dtt/lukuvinkkikirjasto/demo/BaseTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/dao/BookDaoTest.java

* Tests for BookDao
* Logging for DB-operations (BookDao)
* Overall Refactoring
* Remove obsolete object-creation in Main.

Test for BookDao

---

build.gradle
src/main/java/dtt/lukuvinkkikirjasto/demo/database/Database.java
src/main/resources/templates/books.html
src/test/java/dtt/lukuvinkkikirjasto/demo/RunCucumberTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/ServerRule.java
src/test/java/dtt/lukuvinkkikirjasto/demo/StepDefs.java
src/test/resources/features/listAll.feature

how to load test db for tests??

selenium added, spring server starts on tests, but with wrong db

---

src/main/java/dtt/lukuvinkkikirjasto/demo/database/Database.java
src/test/java/dtt/lukuvinkkikirjasto/demo/RunCucumberTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/ServerRule.java

Minor changes:
* Fix broken test
* Use Logger instead of System.out.println()

Fix broken test. Logger instead of Sout.

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/resources/templates/books.html
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/dao/BookDaoTest.java

Controller GET test.
Book with same ISBN can't be added, checked in POST
BookDao, findByIsbn and tests for this

controller tests, book with same isbn cant be added, BookDao tests

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java

Post request goes to test DB fix

post tests to testdb

---

src/main/resources/application.properties
src/test/java/dtt/lukuvinkkikirjasto/demo/BaseTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/StepDefs.java

Manually run Test-initialization.

Fixed broken Cucumber tests

---

src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/resources/db/migration/V3__book_adding_to_database.sql

I don't know anymore. :D

---

src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java

Worshipping meticulous Postgres-gods.

String to int

---

src/main/resources/templates/books.html

cucumber fails for delete as it can't see javascript confirm window.

confirm window for book delete

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/resources/templates/fragments/form.html

Fixed form header when editing.

edit book header fix

---

src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java

Extended line and branch coverage for BookController

extend book controller tests

---

src/main/java/dtt/lukuvinkkikirjasto/demo/database/HerokuListener.java
src/main/resources/templates/fragments/form.html

Fix stop editin button to not throw POST to controller and clean HTML indents. 
Fix herokulistener string matching

fix stop edit button

---

build.gradle
src/main/resources/templates/books.html

Fixed delete a book kukumber test and added one dependency for tests

fix cucumber tests

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/database/HerokuListener.java
src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Book.java
src/main/resources/templates/fragments/form.html
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java

Own POST method for editing books
edited form.html, to match this new POST method
validation while editing.
Notification if successfully edited and error if not.
Tests for controller

Poc for restful put

---

src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Book.java
src/test/java/dtt/lukuvinkkikirjasto/demo/StepDefs.java
src/test/java/dtt/lukuvinkkikirjasto/demo/domain/BookTest.java
src/test/resources/features/newBook.feature

Mun mielestä ne cucumberit oli jo aika kattavat ja en tiedä mistä niiden testi tulokset näkee (codecov?). Tota validation metodia ei käytetty mihinkään Book-luokassa niin otin sen pois. En osannut testata noita try-catch kohtia noissa isbn-validaattoreissa vaikka testailin erilaisii isbn.numeroita ja googlailin.
eli käytin taas jonkun puoltoista tuntii parii hassuu koodi rivii  :D mut hei testikattavuusnousi vähän.

tests for isbn

---

src/main/java/dtt/lukuvinkkikirjasto/demo/bookdata/IsbnApiCaller.java
src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/Dao.java
src/test/java/dtt/lukuvinkkikirjasto/demo/dao/BookDaoTest.java

* Simplify / Refactor Controller & API
* Skeleton models for ApiCaller and for method in Controller API yet to be decided.
I'll continue with the ApiCaller later.

Caller and refactor

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/resources/static/style.css
src/main/resources/templates/book.html
src/main/resources/templates/books.html
src/main/resources/templates/fragments/book_options.html
src/main/resources/templates/fragments/booklist.html
src/main/resources/templates/fragments/head.html
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java

Refactors templates and adds page for single book

Singlebookpage

---

build.gradle
src/main/java/dtt/lukuvinkkikirjasto/demo/bookdata/BookDto.java
src/main/java/dtt/lukuvinkkikirjasto/demo/bookdata/DataCache.java
src/main/java/dtt/lukuvinkkikirjasto/demo/bookdata/IsbnApiCaller.java
src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/resources/templates/book.html
src/main/resources/templates/fragments/book_options.html
src/test/java/dtt/lukuvinkkikirjasto/demo/StepDefs.java
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java
src/test/resources/features/listAll.feature
src/test/resources/features/newBook.feature

* BookDto
* book-template is populated when "info"-button is pressed (and book has ISBN)
* /books/info/{bookId} - endpoint is cached, so smashing the button will not flood Finna API.
* Fixed cucumber tests
Work needed:
* Tests for the new endpoint (MockServer etc. is needed, because of external API calls)
* Re-ordering of book-template...

More work on finna search

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/resources/static/style.css
src/main/resources/templates/book.html
src/main/resources/templates/books.html
src/main/resources/templates/fragments/book_options.html
src/main/resources/templates/fragments/booklist.html

And load all book info on book info load.
And rename book/id path to books/id, to be similar with other paths and requests.
And fix scrolling.

Return button on infopage

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Book.java
src/main/resources/db/migration/V1__Initial_tables.sql
src/main/resources/db/migration/V3__book_adding_to_database.sql
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/dao/BookDaoTest.java

Requires deleting of local databases due to poor operations support in SQlite. :(

Use unique UUID instead of Integer as a primary key for book

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/resources/templates/book.html
src/main/resources/templates/books.html
src/main/resources/templates/fragments/book_options.html
src/test/java/dtt/lukuvinkkikirjasto/demo/dao/BookDaoTest.java

fix for merge hell

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/resources/static/style.css

book edit populates with isbn

---

src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java

fixed tests

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/service/BookService.java

ISBN can be added/edited with empty title and author, if ISBN found, fills them in and overwrites author and title if they were inserted
Valid ISBN that is not found in finna API will be added with "Additional information not found" if title is empty, otherwise it will be added with the forms title and/or author.
Some refactoring.

isbn adding/editing fix

---

src/main/java/dtt/lukuvinkkikirjasto/demo/bookdata/IsbnApiCaller.java
src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/test/java/dtt/lukuvinkkikirjasto/demo/bookdata/IsbnApiCallerRestTest.java
src/test/java/dtt/lukuvinkkikirjasto/demo/bookdata/IsbnApiCallerTest.java

* Tests for API-caller. 
* Minor refactoring.

Tests for API-caller. Minor refactoring.

---

README.md
src/main/resources/static/style.css

Muutin vain tuota style.css tiedoston body{}-kohdan sellaiseksi, että sivun taustalle tulee nätti ponikuva, ja kasvatin keskellä olevan valkoisen laatikon läpinäkyvyyttä. Muut erot johtuvat alaspäin työnnetyistä vanhoista riveistä.

Muutin bodyn taustalle yksisarvisen kuvan.

---

src/main/resources/static/style.css
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java

also background back to rainbow.

more controller tests

---

src/main/resources/static/rainbow.css
src/main/resources/static/style.css
src/main/resources/static/unicorn.css
src/main/resources/templates/books.html
src/main/resources/templates/fragments/head.html

added button to change background.
default is rainbow colors.

Two backgrounds

---

src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/service/BookService.java
src/test/java/dtt/lukuvinkkikirjasto/demo/controller/BookControllerTest.java

BookControl grow branch coverage with few tests

more tests for controller

---

src/main/resources/templates/fragments/head.html

cookies for subpages

---

README.md
src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Book.java

Changes compareTo method in book so that it return different value for books with the same title and different author.

Better compareTo for Book

---

src/main/resources/public/javascript/cookie.js
src/main/resources/templates/fragments/head.html

refactor cookies to own js file from header

refactor cookies

---

src/main/resources/templates/books.html
src/test/java/dtt/lukuvinkkikirjasto/demo/StepDefs.java
src/test/resources/features/markAsRead.feature

Kurkkutestejä

---

README.md
src/main/java/dtt/lukuvinkkikirjasto/demo/LukuvinkkikirjastoApplication.java
src/main/java/dtt/lukuvinkkikirjasto/demo/controller/BookController.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/BookDao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/dao/Dao.java
src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Book.java
src/main/java/dtt/lukuvinkkikirjasto/demo/domain/Fireworks.java
src/main/java/dtt/lukuvinkkikirjasto/demo/service/BookService.java

A bunch of nonfunctional changes that clean up comments and whitespace. The second commit message has more details.

Clean up whitespace and autogenerated comments
